[package]
name = "iokum_tls"
version = "0.0.0"
edition = "2021"
authors = ["Valaphee <iam@valaphee.com>"]
license = "Apache-2.0"
repository = "https://github.com/valaphee/iokum.git"

[dependencies]
openssl = "0.10.55"
rustls = "0.21.2"
