[package]
name = "iokum_nfs"
version = "0.0.0"
edition = "2021"
authors = ["Valaphee <iam@valaphee.com>"]
license = "Apache-2.0"
repository = "https://github.com/valaphee/iokum.git"

[dependencies]
byteorder = "1.4.3"
crc = "3.0.1"
flate2 = "1.0.26"
