[workspace]
members = [
    "asm",
    "bgs",
    "http",
    "mcje",
    "mcje_derive",
    "mojang_session_api",
    "nbt",
    "tls",
]
resolver = "2"

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
