[workspace]
members = [
    #"bgs",
    "http",
    "mcje",
    "mcje_derive",
    "mojang_session_api",
    "nbt",
    "nfs",
    #"ngdp",
    #"pro",
    "proutil",
    #"stu",
    "tls",
]
resolver = "2"
