[package]
name = "httpbogie"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/valaphee/bogie.git"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
futures-util = "0.3.27"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.3", features = ["full"] }
openssl = "0.10.48"
tokio = { version = "1.26.0", features = ["full"] }
tokio-rustls = "0.23.4"
