[package]
name = "staxmcje_derive"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/valaphee/stax.git"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = "2.0.15"
